### ISSUE TITLE
OSM Boundaries Layer

### ISSUE THREAD

**Issue by amyburness** [kartoza/osgs#61]
Symbolise the Boundary layers

- [x]  Labeling

**Comment by seabilwe** [comment]
The boundary layer was filtered to show only admin boundaries at level 4 and the dispute boundary. The labelling was also added to be able to separate each district in the country.

![boundary-full-extent](https://user-images.githubusercontent.com/56301949/145831280-dc68c2e0-0d7c-4d7c-9a85-068b6f5ac4fc.png)
![boundary-labels](https://user-images.githubusercontent.com/56301949/145831292-6132a0fe-f8e6-42f6-8ab5-4be7612429bb.png)
![boundary-labels2](https://user-images.githubusercontent.com/56301949/145831297-43be1aa8-ddaf-4437-825b-3c02779a1a3d.png)
![separated-dispute-and-main-boundaries](https://user-images.githubusercontent.com/56301949/145831303-e1c30503-5fc1-4f90-8ce6-eba179ef80b6.png)

**Comment by seabilwe** [comment]
Admin level between 500m and 8m 
![admin-500-8m](https://user-images.githubusercontent.com/56301949/148353327-70678a49-900e-4b32-818a-812a1470c999.png)

Admin level between 8m and 2m
![admin-8-2m](https://user-images.githubusercontent.com/56301949/148353399-96f88753-35e4-4964-a82a-50ee8ca4a6a9.png)

Admin level between 2m and 500k
![admin-2m-500k](https://user-images.githubusercontent.com/56301949/148353434-6c18a321-9c1d-4957-a456-c056f64c6ba6.png)

Admin level between 500k and 0
![admin-500k-0](https://user-images.githubusercontent.com/56301949/148353482-64b5d27f-18e9-417c-ae89-8d2096d91bac.png)
