### ISSUE TITLE
OSM Places Layer (city&town)

### ISSUE THREAD

**Issue by amyburness** [kartoza/osgs#62]
Symbolise Places

**Comment by seabilwe** [comment]
Place names were categorised as follows (image below) and each feature was given a scale at which it will render as shown in the order in the image below.
![image](https://user-images.githubusercontent.com/56301949/145835208-8c422f43-0819-4ae8-9eae-f0e7687a5a4c.png)

![city](https://user-images.githubusercontent.com/56301949/145835477-2d8499f2-6956-44a5-96a2-9816dbb22088.png)
![suburb](https://user-images.githubusercontent.com/56301949/145835495-fc5eb951-8a68-416e-8d32-ed1c0a6ba301.png)
![town](https://user-images.githubusercontent.com/56301949/145835506-b4065248-469a-444f-ba40-0735947acb0d.png)
![villages](https://user-images.githubusercontent.com/56301949/145835510-b1472a8e-606a-4c8d-b6d9-89147dc0fc54.png)

**Comment by amyburness** [comment]
Added styles to shared project and updated project to have a Finished and Working layer group and map themes to make the updates easy to access.

**Comment by seabilwe** [comment]
Place names between 8m and 2m
![place-names-8-2m](https://user-images.githubusercontent.com/56301949/148353608-47e5cd19-5d8b-4571-b35b-ff7b8c664f4f.png)

Place names between 2m and 150k
![place-names-2m-150k](https://user-images.githubusercontent.com/56301949/148353675-df44a9cc-24b7-42d9-837b-9eed05975bf9.png)

Place names at 150k
![place-names-150k](https://user-images.githubusercontent.com/56301949/148353773-452f7d56-4594-44a3-ba6b-adf418ba8354.png)

Place names at 70k
![place-names-70k](https://user-images.githubusercontent.com/56301949/148353822-2c0e773c-cf78-4db3-bc54-df670ba55896.png)

Place names 35k
![place-names-35k](https://user-images.githubusercontent.com/56301949/148353939-49168fb1-00ca-423d-99d8-876e6a016aa2.png)
