### ISSUE TITLE
OSM Roads Layer

### ISSUE THREAD

**Issue by amyburness** [kartoza/osgs#63]
Symbolise Roads Layer

**Comment by seabilwe** [comment]
For the roads layer, no specific scale was applied to each road feature, but meter at scale was used to reduce the clutter of roads appearing at a near full extent of the map.
![roads-1](https://user-images.githubusercontent.com/56301949/145836297-d7376f60-208d-4319-9bc1-2817df82a7e7.png)
![roads-2](https://user-images.githubusercontent.com/56301949/145836307-4845c585-e00f-4f2d-b73a-545ed6ecf127.png)
![roads-3](https://user-images.githubusercontent.com/56301949/145836316-1382e4fc-15b6-4fd9-94f3-42ec496264e7.png)
![roads-4](https://user-images.githubusercontent.com/56301949/145836319-5b180efc-367e-4f1e-b65d-53ff098a2d9f.png)

**Comment by amyburness** [comment]
Added styles to shared project and updated project to have a Finished and Working layer group and map themes to make the updates easy to access.

**Comment by seabilwe** [comment]
Roads at 15m (Trunk/primary roads)
![trunk-15m](https://user-images.githubusercontent.com/56301949/148354045-d5105e14-6b5e-453b-a084-7fc9633dd34e.png)

Roads between 15m and 1 m (Secondary roads added)
![trunk-second-15-1m](https://user-images.githubusercontent.com/56301949/148354110-62f18d03-9d31-427c-8304-8fa74587e3fa.png)

Tertiary roads added
![trunk-second-tertiary](https://user-images.githubusercontent.com/56301949/148354172-de8f398a-fb03-4e1e-a109-f923f55e2cdf.png)
![trunk-second-tertiary1](https://user-images.githubusercontent.com/56301949/148354223-27982ad6-0c66-4665-934c-e0b58d7f4258.png)

Other roads added
![trunk-second-tertiary-other](https://user-images.githubusercontent.com/56301949/148354271-1029632e-f474-4ad5-a29b-4593d961adbd.png)
![trunk-second-tertiary-other1](https://user-images.githubusercontent.com/56301949/148354281-ecd044fe-c051-46c3-81e5-428b6f0bd46b.png)
