### ISSUE TITLE
OSM Rivers 

### ISSUE THREAD

**Issue by amyburness** [kartoza/osgs#64]
Symbolise rivers

**Comment by seabilwe** [comment]
Rivers were classified into main and small river. 
- Main rivers include: river, stream and canal—`"waterway" IN ('river', 'stream', 'canal')`
- Small rivers include: ditch, drain and pressurised—`"waterway"  NOT IN ('river', 'stream', 'canal')`

![rivers-1](https://user-images.githubusercontent.com/56301949/145833591-c7402a05-0f01-4663-bd22-4db7e0efd3ec.png)
![rivers-2](https://user-images.githubusercontent.com/56301949/145833609-1000d924-312c-4b17-8987-030e1778bd20.png)
![rivers-3](https://user-images.githubusercontent.com/56301949/145833797-066ef46d-b6ea-4290-8900-ea5c96f95cb3.png)

**Comment by amyburness** [comment]
Added styles to shared project and updated project to have a Finished and Working layer group and map themes to make the updates easy to access.

**Comment by seabilwe** [comment]
River and small streams
![streams-river2](https://user-images.githubusercontent.com/56301949/148354476-076a8448-89b6-470e-b4bf-e367e0a929e5.png)
![stream-river](https://user-images.githubusercontent.com/56301949/148354468-a94b19cd-c9a5-4b59-b428-49ff0a66deba.png)

Rivers and man-made water bodies
![stream-river-manmade](https://user-images.githubusercontent.com/56301949/148354528-1f103a7b-5093-4852-82f0-42c4820bfba3.png)
![stream-man-made](https://user-images.githubusercontent.com/56301949/148354522-a216607b-fc14-44ad-b526-336dd79edd05.png)

**Comment by seabilwe** [comment]
- [ ] Play around different blend modes for the rivers, so they blend well with water body layer
![image](https://user-images.githubusercontent.com/56301949/149461265-fe375903-b1a9-4988-9e1e-30a9fb8ea582.png)

**Comment by seabilwe** [comment]
> > * [ ]  Play around different blend modes for the rivers, so they blend well with water body layer
> > 
> > ![image](https://user-images.githubusercontent.com/56301949/149461265-fe375903-b1a9-4988-9e1e-30a9fb8ea582.png)
> 
> Rivers should not flow on top of the dams etc. you can use the geometry generator to hide the rivers where they intersect with the dams etc

Thanks @NyakudyaA
