### ISSUE TITLE
OSM Buildings

### ISSUE THREAD

**Issue by amyburness** [kartoza/osgs#65]
Symbolise Buildings

**Comment by seabilwe** [comment]
The buildings layer has been given a light shade of browns, with shadows that appear between 5000 and 0 in terms of scale. The shadows were created adding 3 different valued offsets to the building features
![buildings-at-25000-to-11000](https://user-images.githubusercontent.com/56301949/145830385-09b5a33d-6dbd-464f-b769-e3ff5f9f1833.png)
![buildings-with-shadow](https://user-images.githubusercontent.com/56301949/145830406-a287f3ca-ae8c-4570-b8a6-c8da87857e09.png)

**Comment by amyburness** [comment]
Added styles to shared project and updated project to have a Finished and Working layer group and map themes to make the updates easy to access.

**Comment by seabilwe** [comment]
For the buildings layer, the second offset that was added has been removed, to reduce the exaggerated 3D effect
![buildings2-shadow](https://user-images.githubusercontent.com/56301949/148354988-55e2f8ea-10e2-4ec7-bde9-2dafac289d9b.png)
